# CircleCI 2.1 configuration for Kanban Metrics
version: 2.1

# Define reusable executors
executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.3.5
    working_directory: ~/kanban-metrics

# Define reusable commands
commands:
  setup_project:
    description: "Setup Ruby project dependencies"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

  store_test_artifacts:
    description: "Store test results and coverage reports"
    steps:
      - store_test_results:
          path: ~/kanban-metrics/tmp/test-results
      - store_artifacts:
          path: ~/kanban-metrics/coverage
          destination: coverage-reports
      - store_artifacts:
          path: ~/kanban-metrics/tmp/test-results
          destination: test-results

# Define jobs
jobs:
  # RSpec Tests with Coverage
  test:
    executor: ruby-executor
    steps:
      - setup_project
      - run:
          name: Run tests with coverage
          command: ./.circleci/scripts/ci-test
      - store_test_artifacts

  # Security Analysis with Brakeman
  security:
    executor: ruby-executor
    steps:
      - setup_project
      - run:
          name: Run security analysis
          command: ./.circleci/scripts/ci-security
      - store_artifacts:
          path: ~/kanban-metrics/tmp/security-results
          destination: security-reports

  # Code Quality with RuboCop
  lint:
    executor: ruby-executor
    steps:
      - setup_project
      - run:
          name: Run code linting
          command: ./.circleci/scripts/ci-lint
      - store_artifacts:
          path: ~/kanban-metrics/tmp/lint-results
          destination: lint-reports

# Define workflows
workflows:
  version: 2
  
  # Primary workflow - run on all commits
  test_and_quality:
    jobs:
      - test
      - security
      - lint